### ISSUE TITLE
AUR packages not found in database

### ISSUE THREAD

**Issue by tbleiker** [asdil12/aurbs#16]
I came across a couple of packages which cannot be build
- [facette](https://aur.archlinux.org/packages/facette/)
- [python2-pysqlite](https://aur.archlinux.org/packages/python2-pysqlite/)

For facette I get the following error:

```
[2015-05-31 17:39:36]  WARNING: AUR-PKG 'facette' not found in local db --> syncing
[2015-05-31 17:39:36]    DEBUG: Stop serving '/var/lib/aurbs/aurstaging/' at port 8024
Traceback (most recent call last):
  File "/usr/bin/aurbs", line 221, in check_pkg
    pkg_local = db.get_pkg(pkgname)
  File "/usr/lib/python3.4/site-packages/aurbs/db.py", line 48, in get_pkg
    raise KeyError("Package '%s' not found in database" % pkgname)
KeyError: "Package 'facette' not found in database"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aurbs", line 228, in check_pkg
    raise PKGSyncNeeded()
aurbs.model.PKGSyncNeeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aurbs", line 395, in <module>
    res = check_pkg(pkg, arch, args.force or args.forceall)
  File "/usr/bin/aurbs", line 236, in check_pkg
    db.sync_pkg(pkgname)
  File "/usr/lib/python3.4/site-packages/aurbs/db.py", line 77, in sync_pkg
    pkg['arch'] = srcinfo['arch']
KeyError: 'arch'
```

**Comment by unixfox** [comment]
I do have something the same error and I don't where it comes from.

**Comment by asdil12** [comment]
python2-pysqlite is not in aur anymore and the facette build fail was not related to this issue.
I think it was related to `PKGBUILD` vs `.SRCINFO` - but now all aur pkgs have a `.SRCINFO` as the AUR server should check on push this using a serverside git hook.
