### ISSUE TITLE
Cant build package with package base

### ISSUE THREAD

**Issue by freaknils** [asdil12/aurbs#25]
If you add a package which is based on a package base f. e. [bareos](https://aur.archlinux.org/pkgbase/bareos/) it wil not build:
```
> aurbs
[2017-05-15 09:52:28]     INFO: Building for architecture x86_64
[2017-05-15 09:52:28]     INFO: Updating x86_64 build root
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
downloading aurstaging.db...
downloading aurstaging.db...
downloading aurstaging.db...
downloading aurstaging.db...
downloading aurstaging.db...
downloading aurstaging.db...
downloading aurstaging.db...
downloading aurstaging.db...
 aurstaging is up to date
:: Starting full system upgrade...
 there is nothing to do
[2017-05-15 09:52:33]  WARNING: AUR-PKG 'bareos-common' not found in local db --> syncing
[2017-05-15 09:52:33]     INFO: Falling back to legacy PKGBUILD parser for pkg 'bareos-common'
Traceback (most recent call last):
  File "/usr/bin/aurbs", line 221, in check_pkg
    pkg_local = db.get_pkg(pkgname)
  File "/usr/lib/python3.6/site-packages/aurbs/db.py", line 48, in get_pkg
    raise KeyError("Package '%s' not found in database" % pkgname)
KeyError: "Package 'bareos-common' not found in database"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aurbs", line 228, in check_pkg
    raise PKGSyncNeeded()
aurbs.model.PKGSyncNeeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aurbs", line 395, in <module>
    res = check_pkg(pkg, arch, args.force or args.forceall)
  File "/usr/bin/aurbs", line 236, in check_pkg
    db.sync_pkg(pkgname)
  File "/usr/lib/python3.6/site-packages/aurbs/db.py", line 68, in sync_pkg
    pkgbuild = pkg_parser.parseFile(tar.extractfile('%s/PKGBUILD' % pkgname))
  File "/usr/lib/python3.6/tarfile.py", line 2073, in extractfile
    tarinfo = self.getmember(member)
  File "/usr/lib/python3.6/tarfile.py", line 1749, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'bareos-common/PKGBUILD' not found"

```

**Comment by asdil12** [comment]
Should be fixed with Version 2.0.0
