### ISSUE TITLE
KeyError: 'provides' after updating to the 2.0.0 version

### ISSUE THREAD

**Issue by unixfox** [asdil12/aurbs#26]
After updating using `make install` to the 2.0.0 version I get this error while running `aurbs`:
```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
downloading aurstaging.db...
downloading aurstaging.db...
downloading aurstaging.db...
downloading aurstaging.db...
 aurstaging is up to date
:: Starting full system upgrade...
 there is nothing to do
[2018-05-26 21:44:20]  WARNING: No build for AUR-PKG 'package-query' --> building
Traceback (most recent call last):
  File "/usr/bin/aurbs", line 397, in <module>
    res = check_pkg(pkg, arch, args.force or args.forceall)
  File "/usr/bin/aurbs", line 253, in check_pkg
    remote_deps = db.filter_dependencies([pkg_local['depends']], local=False)
  File "/usr/lib/python3.6/site-packages/aurbs/db.py", line 270, in filter_dependencies
    pkgs.union(self.get_all_provides())
  File "/usr/lib/python3.6/site-packages/aurbs/db.py", line 67, in get_all_provides
    provides.union(pkg['provides'])
KeyError: 'provides'
```

How can I fix it?

**Comment by asdil12** [comment]
Install version 2.1.0 and run `aurbs -S`

**Comment by unixfox** [comment]
Thank you for your work, it's working fine now!
