### ISSUE TITLE
Can't build python-path

### ISSUE THREAD

**Issue by unixfox** [asdil12/aurbs#27]
I can't build the AUR package `python-path` because aurbs crash when it tries to build it:
```
Traceback (most recent call last):
  File "/usr/bin/aurbs", line 406, in <module>
    res = check_pkg(pkg, arch, args.force or args.forceall)
  File "/usr/bin/aurbs", line 236, in check_pkg
    ver_local = by_name(pkg_build['linkdepends'], dep)['version']
  File "/usr/lib/python3.6/site-packages/aurbs/helper.py", line 48, in by_name
    return filter(lambda i: i['name'] == name, dictlist).__next__()
StopIteration
```

**Comment by asdil12** [comment]
I could not reproduce this error, but try if the latet git version fixes it.
I think this error only occurs, when the pkg is updated and a dependency was added without pkgrel increase.
