### ISSUE TITLE
Unable to build bareos-common

### ISSUE THREAD

**Issue by unixfox** [asdil12/aurbs#28]
You [said that the error was fixed](https://github.com/unixfox/aur/pull/15#issuecomment-392038410) but I still get the error about not finding the package:
```
[2018-05-27 16:55:24]  WARNING: AUR-PKG 'bareos-common' not found in local db --> syncing
[2018-05-27 16:55:25]     INFO: Falling back to legacy PKGBUILD parser for pkg 'bareos-common'
[2018-05-27 16:55:25]    DEBUG: Stop serving '/var/lib/aurbs/aurstaging/' at port 8024
Traceback (most recent call last):
  File "/usr/bin/aurbs", line 308, in sync_pkg
    pkg_local = db.get_pkg(pkgname)
  File "/usr/lib/python3.6/site-packages/aurbs/db.py", line 48, in get_pkg
    raise KeyError("Package '%s' not found in database" % pkgname)
KeyError: "Package 'bareos-common' not found in database"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aurbs", line 315, in sync_pkg
    raise PKGSyncNeeded()
aurbs.model.PKGSyncNeeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aurbs", line 404, in <module>
    sync_pkg(pkg, args.forcesync)
  File "/usr/bin/aurbs", line 326, in sync_pkg
    db.sync_pkg(pkgname)
  File "/usr/lib/python3.6/site-packages/aurbs/db.py", line 88, in sync_pkg
    pkgbuild = pkg_parser.parseFile(tar.extractfile('%s/PKGBUILD' % pkgname))
  File "/usr/lib/python3.6/tarfile.py", line 2074, in extractfile
    tarinfo = self.getmember(member)
  File "/usr/lib/python3.6/tarfile.py", line 1750, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'bareos-common/PKGBUILD' not found"
```
PS: I ran aurbs twice like you said.

**Comment by asdil12** [comment]
With version 2.1.0 running twice should not be needed anymore as aurbs will sync now all pkgs from aur to local db before syncing anything - so the provides and splitpkgs are already known during the first run.

**Comment by asdil12** [comment]
I think the problem here is that you are listing bareos-common in the aurbs.yml but you have to list its pkgbase which is bareos.

The aur will return bareos when aurbs queries bareos-common but aurbs expects a PKG with name bareos.
Because of this aurbs won't find any files.

**Comment by unixfox** [comment]
I tried your suggestion but that doesn't seem to work:
```
[2018-05-28 17:14:05]  WARNING: AUR-PKG 'bareos' not found in local db --> syncing
Traceback (most recent call last):
  File "/usr/bin/aurbs", line 308, in sync_pkg
    pkg_local = db.get_pkg(pkgname)
  File "/usr/lib/python3.6/site-packages/aurbs/db.py", line 48, in get_pkg
    raise KeyError("Package '%s' not found in database" % pkgname)
KeyError: "Package 'bareos' not found in database"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aurbs", line 315, in sync_pkg
    raise PKGSyncNeeded()
aurbs.model.PKGSyncNeeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aurbs", line 404, in <module>
    sync_pkg(pkg, args.forcesync)
  File "/usr/bin/aurbs", line 326, in sync_pkg
    db.sync_pkg(pkgname)
  File "/usr/lib/python3.6/site-packages/aurbs/db.py", line 72, in sync_pkg
    aur.sync(pkgname)
  File "/usr/lib/python3.6/site-packages/aurbs/aur.py", line 52, in sync
    a = get_pkg(pkgname)
  File "/usr/lib/python3.6/site-packages/aurbs/aur.py", line 46, in get_pkg
    raise Exception("Invalid AUR API result for '%s'" % pkgname)
Exception: Invalid AUR API result for 'bareos'
```

**Comment by asdil12** [comment]
I added some more fixes - please try version 2.1.2
