### ISSUE TITLE
Error db.cleanup_orphaned

### ISSUE THREAD

**Issue by specialworld83** [asdil12/aurbs#31]
File "/usr/bin/aurbs", line 351, in <module>
    db.cleanup_orphaned()
  File "/usr/lib/python3.7/site-packages/aurbs/db.py", line 256, in cleanup_orphaned
    if pkg['name'] not in AurBSConfig().aurpkgs:
TypeError: argument of type 'NoneType' is not iterable

**Comment by asdil12** [comment]
You have to define pkgs in config

**Comment by specialworld83** [comment]
File "/usr/bin/aurbs", line 410, in <module>
    sync_pkg(pkg, args.forcesync)
  File "/usr/bin/aurbs", line 322, in sync_pkg
    if version_newer(pkg_local['version'], pkg_aur['version']):
UnboundLocalError: local variable 'pkg_aur' referenced before assignment

**Comment by specialworld83** [comment]
New error:

`[2018-09-05 21:43:43]  WARNING: AUR-PKG 'google-chrome-dev' src-pkg not found --> syncing
Traceback (most recent call last):
  File "/usr/bin/aurbs", line 318, in sync_pkg
    raise PKGSyncNeeded()
aurbs.model.PKGSyncNeeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/aurbs", line 410, in <module>
    sync_pkg(pkg, args.forcesync)
  File "/usr/bin/aurbs", line 332, in sync_pkg
    db.sync_pkg(pkgname)
  File "/usr/lib/python3.7/site-packages/aurbs/db.py", line 72, in sync_pkg
    aur.sync(pkgname)
  File "/usr/lib/python3.7/site-packages/aurbs/aur.py", line 53, in sync
    a = get_pkg(pkgname)
  File "/usr/lib/python3.7/site-packages/aurbs/aur.py", line 43, in get_pkg
    response = urllib.request.urlopen("%s?%s" % (target_url,params)).read()
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
`

**Comment by asdil12** [comment]
Seems like you ran into serverside rate limiting of the AUR API.

**Comment by specialworld83** [comment]
the problem was solved by my hosting. thank you so much

**Comment by specialworld83** [comment]
the problem was solved by my hosting. thank you so much
